Simplify the logic of selecting trials in TrialList
optuna/optuna-dashboard pull request #405
Opened 2023-02-27 13:53 UTC by keisuke-umezawa

## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

NA

## What does this implement/fix? Explain your changes.

2023-02-28 23:43 UTC, c-bata requested changes
Could you rebase on or merge with the latest main branch?

2023-03-02 13:54 UTC, keisuke-umezawa commented
@c-bata 
I rebased against main.

2023-03-03 01:02 UTC, c-bata commented on optuna_dashboard/ts/components/TrialList.tsx
> -                      }
Good catch!

2023-03-03 01:02 UTC, c-bata approved these changes
LGTM!

2023-03-03 01:02 UTC, merged