create base of Preferential UI
optuna/optuna-dashboard pull request #565
Opened 2023-08-17 07:35 UTC by moririn2528

## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

## What does this implement/fix? Explain your changes.

2023-08-17 08:47 UTC, c-bata requested changes
Thank you for your pull request 👍 I left some comments.

2023-08-17 08:47 UTC, c-bata commented on optuna_dashboard/ts/components/StudyDetail.tsx
> +  page?: PageId
Could you avoid using undefined since it will make the logic complex?

2023-08-17 08:47 UTC, c-bata commented on optuna_dashboard/ts/action.ts
> +        }, 1000)
I think you should not call `updateStudyDetail` after this logic since the study will be updated by API polling.

2023-08-17 08:47 UTC, c-bata commented on optuna_dashboard/ts/components/App.tsx
> +                  path={URL_PREFIX + "/studies/:studyId/preference"}
How about assigning the same URL path for `history` and `preference` pages?

2023-08-17 09:27 UTC, moririn2528 commented
Thank you for reviewing. I created a top page that contains a preference and history page, removed setTimeout, and so on.
Could you mind that review again?

2023-08-21 03:27 UTC, c-bata reviewed
Thank you for your pull request. I left some comments.

2023-08-21 03:27 UTC, c-bata commented on optuna_dashboard/ts/components/AppDrawer.tsx
> +    studyId !== undefined ? useStudyDetailValue(studyId) : null
nit: I think you can check both `studyDetail` and `studySummary` to get `is_preferential` property.

2023-08-21 06:32 UTC, c-bata commented on optuna_dashboard/ts/apiClient.ts
> +    .post<RenameStudyResponse>(`/api/studies/${studyId}/preference`, {
```suggestion
    .post<void>(`/api/studies/${studyId}/preference`, {
```

2023-08-21 06:33 UTC, c-bata commented
@moririn2528 Thank you for the update. I will merge this PR after applying my suggestion.

2023-08-21 06:43 UTC, merged