Add Setting to Feedback Screen
optuna/optuna-dashboard pull request #594
Opened 2023-08-31 06:25 UTC by moririn2528

## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

## What does this implement/fix? Explain your changes.

2023-09-11 08:29 UTC, c-bata commented on optuna_dashboard/ts/components/PreferentialTrials.tsx
> +  if (trial === undefined) {
Good catch 👍

2023-09-11 08:29 UTC, c-bata commented on optuna_dashboard/_app.py
> +    def post_component(study_id: int) -> dict[str, Any]:
Could you update the view function's name and api endpoint to elaborate the role of this endpoint?

2023-09-11 08:29 UTC, c-bata commented on optuna_dashboard/_preference_setting.py
> +def register_output_component(
This function is only for preferential module. So could you update the function name?

2023-09-11 08:42 UTC, c-bata commented on optuna_dashboard/_serializer.py
> +        serialized["feedback_artifact_key"] = system_attrs[_SYSTEM_ATTR_FEEDBACK_ARTIFACT_KEY]
Could you update these lines like this?

```suggestion
    serialized["preferential_setting"] = system_attrs[_SYSTEM_ATTR_PREFERENCE_...]
```

2023-09-12 06:59 UTC, moririn2528 commented
Thank you for reviewing.
Since this commitment is too big, I divided API changes #615.

2023-09-15 03:06 UTC, c-bata requested changes

2023-09-15 03:06 UTC, c-bata commented on optuna_dashboard/ts/types/index.d.ts
> +  feedback_artifact_key?: string
I think these attributes do not match with the API response. Does it work?

https://github.com/optuna/optuna-dashboard/blob/76356eb233a754a881ae2fcda11e1c6958388d01/optuna_dashboard/_serializer.py#L169-L171

2023-09-15 05:50 UTC, c-bata commented on optuna_dashboard/ts/action.ts
> +    artifact_key?: string
Could you type the component like below?

```
type FeedbackComponentNote = {
    output_type: "note",
}

type FeedbackComponentArtifact = {
    output_type: "artifact",
    artifact_key: string
}

FeedbackComponentType = FeedbackComponentArtifact | FeedbackComponentNote
```

2023-09-15 06:58 UTC, c-bata commented on optuna_dashboard/ts/action.ts
> +    reportFeedbackComponentAPI(studyId, compoennt_type).catch((err) => {
Could you update the studyDetail as well?

2023-09-15 06:59 UTC, c-bata commented on optuna_dashboard/ts/apiClient.ts
> +}
A nit, but I think it's easier to update Python API response schema than creating this convert function.

2023-09-15 08:56 UTC, c-bata commented on optuna_dashboard/ts/apiClient.ts
> +        : { type: "artifact", artifact_key: component_type.artifact_key }
How about updating a JSON API to simplify this like below?

```suggestion
      `/api/studies/${studyId}/preference_feedback_component`,
      component_type
```

2023-09-15 09:19 UTC, c-bata commented on optuna_dashboard/ts/components/PreferentialTrials.tsx
> +export const OutputContent: FC<{
How about splitting the file to PreferentialOutputContent since this component is imported from multiple files.

2023-09-19 02:24 UTC, c-bata reviewed
Looks almost good to me. I left some comments.

2023-09-19 02:24 UTC, c-bata commented on optuna_dashboard/ts/components/AppDrawer.tsx
> +                <ListItemText primary="note" sx={styleListItemText} />
I think you should not change this.


<img width="239" alt="Screenshot 2023-09-19 11 20 27" src="https://github.com/optuna/optuna-dashboard/assets/5564044/2deab6de-75f7-4afc-acbd-eb856069ec4a">

```suggestion
                <ListItemText primary="Note" sx={styleListItemText} />
```

2023-09-19 02:24 UTC, c-bata commented on optuna_dashboard/ts/components/AppDrawer.tsx
> +            <ListItem key="note" disablePadding sx={styleListItem}>
A nit.

```suggestion
            <ListItem key="Note" disablePadding sx={styleListItem}>
```

2023-09-19 02:24 UTC, c-bata commented on optuna_dashboard/ts/apiClient.ts
> +        },
I think you should not insert the default value on `apiClient`. How about inserting a default value on the JSON API layer or making this field allows undefined?

2023-09-19 05:14 UTC, c-bata approved these changes

2023-09-19 05:14 UTC, merged