Add Preference Graph
optuna/optuna-dashboard pull request #601
Opened 2023-09-06 09:28 UTC by moririn2528

## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

## What does this implement/fix? Explain your changes.

2023-09-07 09:59 UTC, moririn2528 commented on webpack.config.js
> +      },
In this file, I change only this block. Others are changed by formatter.

2023-09-08 09:47 UTC, c-bata requested changes
Thank you for your pull request. I left some comments.

2023-09-08 09:47 UTC, c-bata commented on optuna_dashboard/ts/components/AppDrawer.tsx
> +                    primary="PreferenceGraph"
How about this?

```suggestion
                    primary="Preferences (Graph)"
```

2023-09-08 09:47 UTC, c-bata commented on optuna_dashboard/ts/components/AppDrawer.tsx
> +                    primary="PreferenceGraph"
I actually do not prefer "PreferenceHistory" and "HumanInTheLoop". At least there should be a space between each word. What do you think?

2023-09-08 09:47 UTC, c-bata commented on optuna_dashboard/ts/types/index.d.ts
> +declare module "*.css"
Could you move this to the top of this file?

2023-09-08 09:47 UTC, c-bata commented on optuna_dashboard/ts/components/PreferentialGraph.tsx
> +          style: { stroke: isDarkMode ? "#fff" : "#000" },
Can we use theme.palette.background color instead?

2023-09-11 05:49 UTC, c-bata reviewed
Looks almost good to me. Left some comments.

2023-09-11 05:49 UTC, c-bata commented on optuna_dashboard/ts/components/PreferentialGraph.tsx
> +): [number, number][] {
How about using arrow function expression?

2023-09-11 05:49 UTC, c-bata commented on optuna_dashboard/ts/components/AppDrawer.tsx
> +            {studyDetail?.is_preferential && (
How about checking `studySummary?.is_preferential` as well? Perhaps it is better to define the function like below.

https://github.com/optuna/optuna-dashboard/blob/238dffa80f347081fb93b77436c9c21dd4153439/optuna_dashboard/ts/state.ts#L82-L88

2023-09-11 08:14 UTC, c-bata approved these changes
LGTM!

2023-09-11 08:14 UTC, merged