add preference feedback component api
optuna/optuna-dashboard pull request #615
Opened 2023-09-12 06:31 UTC by moririn2528

## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [ ] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

## What does this implement/fix? Explain your changes.

2023-09-12 08:08 UTC, contramundum53 commented on optuna_dashboard/_preference_setting.py
> +) -> None:
If the user specifies `component_type="Artifact"` without setting the `artifact_key`, the current behavior is to set an empty string to `artifact_key`. As a result, the artifact will not be shown, and the user may not know what's wrong.

How about setting the default argument of `artifact_key` to `None` and perform a check here?

2023-09-12 08:10 UTC, contramundum53 commented on optuna_dashboard/_preference_setting.py
> +    OUTPUT_COMPONENT_TYPE = Literal["Note", "Artifact"]
How about using lower-case, to be consistent with "minimum"/"maximum" used in optuna?

2023-09-12 08:57 UTC, contramundum53 approved these changes
LGTM!

2023-09-12 08:58 UTC, contramundum53 commented
Please format the code by 
```
black .
isort .
```

2023-09-14 01:34 UTC, c-bata commented on optuna_dashboard/_app.py
> +        )
I think you need to set `response.status = 204` to make tests pass.

2023-09-14 01:36 UTC, c-bata commented on optuna_dashboard/_app.py
> +    def put_component(study_id: int) -> dict[str, Any]:
Could you update the view function name to elaborate the role of this api endpoint?

2023-09-14 01:41 UTC, c-bata commented on optuna_dashboard/_serializer.py
>      if serialized["is_preferential"]:
I think you can merge this if-statement block.

2023-09-14 04:05 UTC, contramundum53 approved these changes
LGTM!

2023-09-14 05:58 UTC, c-bata requested changes

2023-09-14 05:58 UTC, c-bata commented on optuna_dashboard/_preference_setting.py
> +    """
How about updating the function name and docstring like below?

```suggestion
def register_preference_feedback_component(
    study: PreferentialStudy,
    component_type: OUTPUT_COMPONENT_TYPE,
    user_attr_artifact_key: str | None = None,
) -> None:
    """Register a preference feedback component to the study.
    
    With this feature, you can change the component, displayed on the
    human feedback pages. By default, the Markdown note (``component_type="note"``)
    is displayed.  If you specify ``component_type="user_attr"``, the viewer for the
    specified artifact file will be displayed.

    Args:
        study:
            The study to register the preference feedback component.
        component_type:
            The component type, displayed on the human feedback pages
            (default: ``note``).
        user_attr_artifact_key:
            This option is required when the ``component_type`` is ``"artifact``.
            The user attribute, which is specified this field, must contain the
            ``artifact`id you want to display on the human feedback page.
    """
```

2023-09-14 07:24 UTC, c-bata approved these changes
LGTM.

2023-09-14 07:26 UTC, c-bata reviewed
Now I noticed that we need to update the api reference below since this PR adds a public api. Could you update it?
https://optuna-dashboard--615.org.readthedocs.build/en/615/api.html#preferential-optimization

2023-09-14 07:26 UTC, c-bata commented on optuna_dashboard/_preference_setting.py
> +def register_preference_feedback_component_type(
```suggestion
def register_preference_feedback_component(
```

2023-09-14 08:00 UTC, c-bata commented on docs/api.rst
> +   optuna_dashboard._preference_setting.register_preference_feedback_component
You need to export from the public module. Could you update the `__init__.py` as well?

```suggestion
   optuna_dashboard.register_preference_feedback_component
```

2023-09-14 08:12 UTC, merged