Add e2e test for loading journal storage in standalone app
optuna/optuna-dashboard pull request #782
Opened 2024-01-27 05:42 UTC by keisuke-umezawa

## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [ ] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

To follow-up on https://github.com/optuna/optuna-dashboard/pull/732

## What does this implement/fix? Explain your changes.

Add e2e test for loading journal storage in standalone app

2024-01-29 07:42 UTC, c-bata commented
@gen740 @nabenabe0928 Could you review this PR?

2024-02-02 04:25 UTC, gen740 requested changes
Thank you for your PR!
I have a question regarding `test_load_rdb_storage` and `test_load_journal_storage`. They share the same code and test the same functionality. How about using a pytest fixture?

2024-02-09 00:49 UTC, keisuke-umezawa commented
@gen740 
I updated it. Could you check it again?

2024-02-21 09:04 UTC, nabenabe0928 reviewed
Thank you for the PR and sorry for the late response, I left minor suggestions!

2024-02-21 09:04 UTC, nabenabe0928 commented on e2e_tests/test_standalone/test_study_list.py
> +)
[suggestion] How about bundling them together?
```suggestion
def create_rdb_storage_file(filename: str, study_name: str, storage_type: str):
    if storage_type == "rdb":
        storage = optuna.storages.RDBStorage(f"sqlite:///{filename}")
    elif storage_type == "journal":
        storage = optuna.storages.JournalStorage(
            optuna.storages.JournalFileStorage(f"{filename}"),
        )
    else:
        assert False, f"Got an unexpected storage_type={storage_type}."

    study = optuna.create_study(study_name=study_name, storage=storage)

    def objective(trial: optuna.Trial) -> float:
        x1 = trial.suggest_float("x1", 0, 10)
        x2 = trial.suggest_float("x2", 0, 10)
        return (x1 - 2) ** 2 + (x2 - 5) ** 2

    study.optimize(objective, n_trials=100)


@pytest.mark.parametrize("storage_type", ["rdb", "journal"])
```

2024-03-07 09:32 UTC, keisuke-umezawa commented
@nabenabe0928 @gen740 I fixed it. Could you review it again?

2024-03-18 05:50 UTC, gen740 approved these changes
Sorry for the late reply. LGTM!

2024-03-22 08:08 UTC, nabenabe0928 approved these changes
Thank you for the changes, LGTM!

2024-03-22 08:08 UTC, merged